const TRAVEL_DATA = [
  {
    id: 1,
    title: "New Delhi",
    routeName: "new_delhi",
    items: [
      {
        ID: 1,
        "Crawl Timestamp": "2021-09-19 23:07:23 +0000",
        "Package Name": "A Grand Week in North East - Lachung Special",
        Image_Url:
          "https://images.unsplash.com/photo-1637083245666-23ac7bd66809?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDR8RnpvM3p1T0hONnd8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60",
        Package_Type: "Deluxe",
        Company: "Tralive",
        Destination: "Gangtok|Lachung|Gangtok|Darjeeling",
        Itinerary: "2N Gangtok . 2N Lachung . 1N Gangtok . 2N Darjeeling",
        "Places Covered": "Gangtok|Lachung|Gangtok|Darjeeling",
        Travel_Date: "02-10-2021",
        Hotel_Details:
          "Lemon Tree Hotel  Gangtok:4.2|Summit Alpine Resort, Lachung- MMT Holidays Special:4.2|Lemon Tree Hotel  Gangtok:4.4|Ramada by Wyndham Darjeeling Gandhi Road:",
        Start_City: "New Delhi",
        Airline: "IndiGo",
        "Flight Stops": "",
        "Onwards Return Flight Time": "14 : 00-16 : 05",
        Meals: "",
        Price_Per_Two_Persons: 71350,
        Per_Person_Price: 35675,
        "Sightseeing Places Covered":
          " Baba Mandir | MG Road - Walk | Visit to Lake Tsomgo with Yak Safari | Snacks at Changu lake (Winter Special) | Yumthang Valley | Hot Spring ",
        "Initial Payment For Booking": "",
        "Cancellation Rules":
          "Cancellation any time after making the 1st payment instalment till the 2nd payment date:The entire amount paid as 1st payment instalment (deposit) would be non-refundable.Cancellation after 2nd payment instalment and before 3rd or final payment date:The total amount that was due at the 2nd payment instalment as per your payment schedule would be non-refundable; anything that you have paid over and above this amount would be refundable.Cancellation after 3rd or final payment date:The full amount paid by you would be non-refundable.",
        "Date Change Rules": "",
        FIELD23: "",
        FIELD24: "",
        FIELD25: "",
      },
      {
        ID: 2,
        "Crawl Timestamp": "2021-09-24 11:46:20 +0000",
        "Package Name": "Stunning Kashmir Holiday",
        Image_Url:
          "https://images.unsplash.com/photo-1630391886685-b3ef8d10de53?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=435&q=80",
        Package_Type: "Standard",
        Company: "Tralive",
        Destination: "Gulmarg|Pahalgam|Srinagar",
        Itinerary: "1N Gulmarg . 2N Pahalgam . 2N Srinagar",
        "Places Covered": "Gulmarg|Pahalgam|Srinagar",
        Travel_Date: "26-10-2021",
        Hotel_Details: "Alpine Ridge:3.4|Hotel Hilltop:3.6|The Pride Inn:4.2",
        Start_City: "New Delhi",
        Airline: "IndiGo|IndiGo",
        "Flight Stops": "",
        "Onwards Return Flight Time": "06 : 30-09 : 10|12 : 45-14 : 20",
        Meals: "",
        Price_Per_Two_Persons: 31933,
        Per_Person_Price: 15966.5,
        "Sightseeing Places Covered":
          " Gondola Point | Avantipura Ruins | Mughal Gardens | Cheshma Shahi | Nishat Bagh | Shalimar Garden | Shankaracharya Temple | Dal Lake ",
        "Initial Payment For Booking": "",
        "Cancellation Rules":
          "Cancellation any time after making the 1st payment instalment till the 2nd payment date:The entire amount paid as 1st payment instalment (deposit) would be non-refundable.Cancellation after 2nd payment instalment and before 3rd or final payment date:The total amount that was due at the 2nd payment instalment as per your payment schedule would be non-refundable; anything that you have paid over and above this amount would be refundable.Cancellation after 3rd or final payment date:The full amount paid by you would be non-refundable.",
        "Date Change Rules": "",
        FIELD23: "",
        FIELD24: "",
        FIELD25: "",
      },
      {
        ID: 3,
        "Crawl Timestamp": "2021-09-24 11:46:20 +0000",
        "Package Name": "Stunning Kashmir Holiday",
        Image_Url:
          "https://images.unsplash.com/photo-1641449825304-c966bb0ad1fa?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80",
        Package_Type: "Standard",
        Company: "Tralive",
        Destination: "Gulmarg|Pahalgam|Srinagar",
        Itinerary: "1N Gulmarg . 2N Pahalgam . 2N Srinagar",
        "Places Covered": "Gulmarg|Pahalgam|Srinagar",
        Travel_Date: "26-10-2021",
        Hotel_Details: "Alpine Ridge:3.4|Hotel Hilltop:3.6|The Pride Inn:4.2",
        Start_City: "New Delhi",
        Airline: "IndiGo|IndiGo",
        "Flight Stops": "",
        "Onwards Return Flight Time": "06 : 30-09 : 10|12 : 45-14 : 20",
        Meals: "",
        Price_Per_Two_Persons: 31933,
        Per_Person_Price: 15966.5,
        "Sightseeing Places Covered":
          " Gondola Point | Avantipura Ruins | Mughal Gardens | Cheshma Shahi | Nishat Bagh | Shalimar Garden | Shankaracharya Temple | Dal Lake ",
        "Initial Payment For Booking": "",
        "Cancellation Rules":
          "Cancellation any time after making the 1st payment instalment till the 2nd payment date:The entire amount paid as 1st payment instalment (deposit) would be non-refundable.Cancellation after 2nd payment instalment and before 3rd or final payment date:The total amount that was due at the 2nd payment instalment as per your payment schedule would be non-refundable; anything that you have paid over and above this amount would be refundable.Cancellation after 3rd or final payment date:The full amount paid by you would be non-refundable.",
        "Date Change Rules": "",
        FIELD23: "",
        FIELD24: "",
        FIELD25: "",
      },
      {
        ID: 4,
        "Crawl Timestamp": "2021-09-19 23:07:23 +0000",
        "Package Name": "A Grand Week in North East - Lachung Special",
        Image_Url:
          "https://images.unsplash.com/photo-1641725814339-58f7c1fd40e6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
        Package_Type: "Deluxe",
        Company: "Tralive",
        Destination: "Gangtok|Lachung|Gangtok|Darjeeling",
        Itinerary: "2N Gangtok . 2N Lachung . 1N Gangtok . 2N Darjeeling",
        "Places Covered": "Gangtok|Lachung|Gangtok|Darjeeling",
        Travel_Date: "02-10-2021",
        Hotel_Details:
          "Lemon Tree Hotel  Gangtok:4.2|Summit Alpine Resort, Lachung- MMT Holidays Special:4.2|Lemon Tree Hotel  Gangtok:4.4|Ramada by Wyndham Darjeeling Gandhi Road:",
        Start_City: "New Delhi",
        Airline: "IndiGo",
        "Flight Stops": "",
        "Onwards Return Flight Time": "14 : 00-16 : 05",
        Meals: "",
        Price_Per_Two_Persons: 71350,
        Per_Person_Price: 35675,
        "Sightseeing Places Covered":
          " Baba Mandir | MG Road - Walk | Visit to Lake Tsomgo with Yak Safari | Snacks at Changu lake (Winter Special) | Yumthang Valley | Hot Spring ",
        "Initial Payment For Booking": "",
        "Cancellation Rules":
          "Cancellation any time after making the 1st payment instalment till the 2nd payment date:The entire amount paid as 1st payment instalment (deposit) would be non-refundable.Cancellation after 2nd payment instalment and before 3rd or final payment date:The total amount that was due at the 2nd payment instalment as per your payment schedule would be non-refundable; anything that you have paid over and above this amount would be refundable.Cancellation after 3rd or final payment date:The full amount paid by you would be non-refundable.",
        "Date Change Rules": "",
        FIELD23: "",
        FIELD24: "",
        FIELD25: "",
      },
      {
        ID: 5,
        "Crawl Timestamp": "2021-09-17 08:11:19 +0000",
        "Package Name": "Stupendous Holiday in Kashmir",
        Image_Url:
          "https://images.unsplash.com/photo-1626698429935-bffe144c23f2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDEwfEZ6bzN6dU9ITjZ3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
        Package_Type: "Premium",
        Company: "Tralive",
        Destination: "Srinagar|Gulmarg|Pahalgam|Srinagar",
        Itinerary: "1N Srinagar . 2N Gulmarg . 2N Pahalgam . 2N Srinagar",
        "Places Covered": "Srinagar|Gulmarg|Pahalgam|Srinagar",
        Travel_Date: "26-09-2021",
        Hotel_Details:
          "The Orchard Retreat & Spa:4.6|The Khyber Himalayan Resort & Spa:4.6|WelcomHotel Pine N Peak Pahalgam - Member ITC Hotel Group:4.1|Radisson Srinagar:3.9",
        Start_City: "New Delhi",
        Airline: "IndiGo",
        "Flight Stops": "",
        "Onwards Return Flight Time": "10 : 45-15 : 00",
        Meals: "",
        Price_Per_Two_Persons: 72634,
        Per_Person_Price: 36317,
        "Sightseeing Places Covered":
          " Dal Lake | Gondola Point | Avantipura Ruins ",
        "Initial Payment For Booking": "",
        "Cancellation Rules":
          "Cancellation any time after making the 1st payment instalment till the 2nd payment date:The entire amount paid as 1st payment instalment (deposit) would be non-refundable.Cancellation after 2nd payment instalment and before 3rd or final payment date:The total amount that was due at the 2nd payment instalment as per your payment schedule would be non-refundable; anything that you have paid over and above this amount would be refundable.Cancellation after 3rd or final payment date:The full amount paid by you would be non-refundable.",
        "Date Change Rules": "",
        FIELD23: "",
        FIELD24: "",
        FIELD25: "",
      },
      {
        ID: 6,
        "Crawl Timestamp": "2021-09-23 10:36:27 +0000",
        "Package Name": "A Retreat to Ooty and Kodaikanal",
        Image_Url:
          "https://images.unsplash.com/photo-1626698369649-7094f7155e44?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDh8RnpvM3p1T0hONnd8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60",
        Package_Type: "Standard",
        Company: "Tralive",
        Destination: "Ooty|Kodaikanal",
        Itinerary: "2N Ooty . 2N Kodaikanal",
        "Places Covered": "Ooty|Kodaikanal",
        Travel_Date: "11-10-2021",
        Hotel_Details: "Hotel Meadows Residency:4.4|Hotel Jem Valley:3.8",
        Start_City: "New Delhi",
        Airline: "Air India|IndiGo",
        "Flight Stops": "",
        "Onwards Return Flight Time": "09 : 05-10 : 30|14 : 20-16 : 15",
        Meals: "",
        Price_Per_Two_Persons: 25915,
        Per_Person_Price: 12957.5,
        "Sightseeing Places Covered":
          " Doddabetta Peak | Ooty Botanical Gardens | Sim's Park | Dolphins Nose | Lamb's Rock | Tea Museum | Kodaikanal Lake | Pillar Rock | Coakers Walk | Bear Shola Fall | Bryant Park | Kodaikanal Lake ",
        "Initial Payment For Booking": "",
        "Cancellation Rules":
          "Cancellation any time after making the 1st payment instalment till the 2nd payment date:The entire amount paid as 1st payment instalment (deposit) would be non-refundable.Cancellation after 2nd payment instalment and before 3rd or final payment date:The total amount that was due at the 2nd payment instalment as per your payment schedule would be non-refundable; anything that you have paid over and above this amount would be refundable.Cancellation after 3rd or final payment date:The full amount paid by you would be non-refundable.",
        "Date Change Rules": "",
        FIELD23: "",
        FIELD24: "",
        FIELD25: "",
      },
      {
        ID: 7,
        "Crawl Timestamp": "2021-09-19 01:41:29 +0000",
        "Package Name": "Leisurely Retreat in Divine Dharamshala",
        Image_Url:
          "https://images.unsplash.com/photo-1638496960047-ebdfa98a50ec?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE0fEZ6bzN6dU9ITjZ3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
        Package_Type: "Deluxe",
        Company: "Tralive",
        Destination: "Dharamshala",
        Itinerary: "3N Dharamshala",
        "Places Covered": "Dharamshala",
        Travel_Date: "30-09-2021",
        Hotel_Details:
          "Little Mastiff Dharamshala - Unit Of Pong View Hotel:3.9",
        Start_City: "New Delhi",
        Airline: "",
        "Flight Stops": "",
        "Onwards Return Flight Time": "",
        Meals: "",
        Price_Per_Two_Persons: 13427,
        Per_Person_Price: 6713.5,
        "Sightseeing Places Covered":
          " Dalai Lama temple | Bhagsu falls | Church of St. John | War Memorial | Kangra Art Museum | Cricket Stadium | Norbulingka Institute | Kangra Art Museum ",
        "Initial Payment For Booking": "",
        "Cancellation Rules":
          "This cancellation policy is applicable for bookings made for Weekend Getaways through the MakeMyTrip platform   If the booking is made 15 days prior to the travel date (i.e. the date on which the customer is travelling):  When the customer has booked a weekend getaway 15 days (inclusive of the travel date) prior to the travel date, the customer is eligible to avail the benefit of this offer.At the time of making the payment while booking the package, the customer shall have the option of either paying in total or in instalments. If the customer chooses to make the payment in total and cancels the booking within 24 hours of making the payment, the customer shall be entitled to get the full refund under this offer. In case of any flight bookings, MakeMyTrip shall, in its sole discretion, refund partial booking amount to the customer. Full refund under the offer is not applicable on Air Asia, Scoot Airlines, Nok-Scoot and Tiger Australia.  If a customer chooses to make the payment in instalments and cancels the booking thereafter, MakeMyTrip shall provide the refund in the following manner:When the customer has made 1st instalment of the booking amount and the booking is cancelled within 24 hours of making the booking, MakeMyTrip shall refund the full amount paid in the 1st instalment. However, In case of any flight bookings, MakeMyTrip shall, in its sole discretion, refund partial booking amount to the customer. Full refund under the offer is not applicable on Air Asia, Scoot Airlines, Nok-Scoot & Tiger Australia.  When the customer has made 1st instalment of the booking amount and the booking is cancelled after 24 hours of making the booking but before making the 2nd instalment, the entire 1st instalment shall be non-refundable.  When the customer cancels the booking upon paying the 2nd instalment but before paying the 3rd instalment, the amount of 1st and 2nd instalment as paid by the customer shall be non-refundable. However, if the customer has paid an amount over and above the amount to be paid for the 1st and 2nd instalment, MakeMyTrip shall refund the said amount.  When the customer cancels the booking upon paying the 3rd instalment, the entire booking amount paid shall be non-refundable.  If the booking is made within 15 days from the travel date:   When the customer has made 1st instalment of the booking amount and the booking is cancelled before making the 2nd instalment, the entire 1st instalment shall be non-refundable.  When the customer cancels the booking upon paying the 2nd instalment but before paying the 3rd instalment, the amount of 1st and 2nd instalment as paid by the customer shall be non-refundable. However, if the customer has paid an amount over and above the amount to be paid for the 1st and 2nd instalment, MakeMyTrip shall refund the said amount.When the customer cancels the booking upon paying the 3rd instalment, the entire booking amount paid shall be non-refundable.",
        "Date Change Rules": "",
        FIELD23: "",
        FIELD24: "",
        FIELD25: "",
      },
      {
        ID: 8,
        "Crawl Timestamp": "2021-09-23 11:01:50 +0000",
        "Package Name": "Best of Bali - 5 Nights",
        Image_Url:
          "https://images.unsplash.com/photo-1640767514388-eef1b79eb036?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDEzfEZ6bzN6dU9ITjZ3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
        Package_Type: "Deluxe",
        Company: "Tralive",
        Destination: "Bali",
        Itinerary: "5N Bali",
        "Places Covered": "Bali",
        Travel_Date: "12-10-2021",
        Hotel_Details: "Kuta Central Park Hotel - MMT Special:4.0",
        Start_City: "New Delhi",
        Airline:
          "Malaysia Airlines|Malaysia Airlines|Malaysia Airlines|Malaysia Airlines",
        "Flight Stops": "",
        "Onwards Return Flight Time":
          "23 : 35-07 : 35|09 : 00-12 : 05|12 : 55-16 : 00|19 : 50-22 : 25",
        Meals: "",
        Price_Per_Two_Persons: 73625,
        Per_Person_Price: 36812.5,
        "Sightseeing Places Covered":
          " Photoshoot at Tanah Lot | Guided Kintamani Tour with Indonesian Lunch and Private Transfers | Guided Tanah Lot Tour at Sunset with Private Transfers | Watersports at Tanjung Benoa Beach with Shared Transfers ",
        "Initial Payment For Booking": "",
        "Cancellation Rules":
          "Cancellation any time after making the 1st payment instalment till the 2nd payment date:The entire amount paid as 1st payment instalment (deposit) would be non-refundable.Cancellation after 2nd payment instalment and before 3rd or final payment date:The total amount that was due at the 2nd payment instalment as per your payment schedule would be non-refundable; anything that you have paid over and above this amount would be refundable.Cancellation after 3rd or final payment date:The full amount paid by you would be non-refundable.",
        "Date Change Rules": "",
        FIELD23: "",
        FIELD24: "",
        FIELD25: "",
      },
      {
        ID: 9,
        "Crawl Timestamp": "2021-09-20 06:11:55 +0000",
        "Package Name": "A Vacation to South - Durga Puja Special",
        Image_Url:
          "https://images.unsplash.com/photo-1631555758627-2b93bffeaf23?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE4fEZ6bzN6dU9ITjZ3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
        Package_Type: "Premium",
        Company: "Tralive",
        Destination: "Mysore|Coorg|Ooty",
        Itinerary: "1N Mysore . 2N Coorg . 2N Ooty",
        "Places Covered": "Mysore|Coorg|Ooty",
        Travel_Date: "12-10-2021",
        Hotel_Details:
          "Country Inn And Suites By Radisson, Mysore:4.2|The Windflower Resorts & Spa:4|Western Valley Resorts:4.2",
        Start_City: "New Delhi",
        Airline: "IndiGo",
        "Flight Stops": "",
        "Onwards Return Flight Time": "05 : 05-07 : 50",
        Meals: "",
        Price_Per_Two_Persons: 38757,
        Per_Person_Price: 19378.5,
        "Sightseeing Places Covered":
          " Mysore Palace | Chamundi Hills | Dubare Elephant Camp | Tibetan Temple | Abbey falls | Rajaâ€™s Seat | Talacauvery Bhagamandala ",
        "Initial Payment For Booking": "",
        "Cancellation Rules":
          "Cancellation any time after making the 1st payment instalment till the 2nd payment date:The entire amount paid as 1st payment instalment (deposit) would be non-refundable.Cancellation after 2nd payment instalment and before 3rd or final payment date:The total amount that was due at the 2nd payment instalment as per your payment schedule would be non-refundable; anything that you have paid over and above this amount would be refundable.Cancellation after 3rd or final payment date:The full amount paid by you would be non-refundable.",
        "Date Change Rules": "",
        FIELD23: "",
        FIELD24: "",
        FIELD25: "",
      },
      {
        ID: 10,
        "Crawl Timestamp": "2021-09-17 23:22:11 +0000",
        "Package Name": "Goa 6N stay - with Transfers (for Bigger Groups)",
        Image_Url:
          "https://images.unsplash.com/photo-1630392307670-0cb136f78f27?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDIxfEZ6bzN6dU9ITjZ3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
        Package_Type: "Luxury",
        Company: "Tralive",
        Destination: "Goa",
        Itinerary: "6N Goa",
        "Places Covered": "Goa",
        Travel_Date: "30-09-2021",
        Hotel_Details: "Novotel Goa Resort & Spa:4.1",
        Start_City: "New Delhi",
        Airline: "Spicejet",
        "Flight Stops": "",
        "Onwards Return Flight Time": "11 : 35-13 : 00",
        Meals: "",
        Price_Per_Two_Persons: 37512,
        Per_Person_Price: 18756,
        "Sightseeing Places Covered": "",
        "Initial Payment For Booking": "",
        "Cancellation Rules":
          "Cancellation any time after making the 1st payment instalment till the 2nd payment date:The entire amount paid as 1st payment instalment (deposit) would be non-refundable.Cancellation after 2nd payment instalment and before 3rd or final payment date:The total amount that was due at the 2nd payment instalment as per your payment schedule would be non-refundable; anything that you have paid over and above this amount would be refundable.Cancellation after 3rd or final payment date:The full amount paid by you would be non-refundable.",
        "Date Change Rules": "",
        FIELD23: "",
        FIELD24: "",
        FIELD25: "",
      },
      {
        ID:11,
        "Crawl Timestamp": "2021-09-16 19:51:59 +0000",
        "Package Name": "Kodaikanal with Ooty Special (Honeymoon Special)",
        Image_Url:
          "https://images.unsplash.com/photo-1641547827212-22eccac51a36?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDI1fEZ6bzN6dU9ITjZ3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
        Package_Type: "Premium",
        Company: "Tralive",
        Destination: "Ooty|Kodaikanal|Munnar",
        Itinerary: "2N Ooty . 2N Kodaikanal . 2N Munnar",
        "Places Covered": "Ooty|Kodaikanal|Munnar",
        Travel_Date: "06-10-2021",
        Hotel_Details:
          "Gem Park:4.0|The Tamara Kodai:|Parakkat Nature Resorts:",
        Start_City: "New Delhi",
        Airline: "IndiGo|Spicejet",
        "Flight Stops": "",
        "Onwards Return Flight Time": "11 : 55-13 : 50|11 : 55-14 : 05",
        Meals: "",
        Price_Per_Two_Persons: 56929,
        Per_Person_Price: 28464.5,
        "Sightseeing Places Covered":
          " Ooty Lake | Doddabetta Peak | Ooty Botanical Gardens | Sim's Park | Dolphins Nose | Lamb's Rock | Tea Museum | South India - Convenience Value Pack - Sedan | Tour Around Avalanche Lake (With Transfers) | Pillar Rock | Coakers Walk | Bear Shola Fall | Bryant Park | Kodaikanal Lake ",
        "Initial Payment For Booking": "",
        "Cancellation Rules":
          "Cancellation any time after making the 1st payment instalment till the 2nd payment date:The entire amount paid as 1st payment instalment (deposit) would be non-refundable.Cancellation after 2nd payment instalment and before 3rd or final payment date:The total amount that was due at the 2nd payment instalment as per your payment schedule would be non-refundable; anything that you have paid over and above this amount would be refundable.Cancellation after 3rd or final payment date:The full amount paid by you would be non-refundable.",
        "Date Change Rules": "",
        FIELD23: "",
        FIELD24: "",
        FIELD25: "",
      },
      {
        ID: 12,
        "Crawl Timestamp": "2021-09-18 00:57:10 +0000",
        "Package Name": "Fabulous North East (Lachung & Pelling Special)",
        Image_Url:
          "https://images.unsplash.com/photo-1640020374654-ec88277ef55e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDI4fEZ6bzN6dU9ITjZ3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
        Package_Type: "Deluxe",
        Company: "Tralive",
        Destination: "Gangtok|Lachung|Gangtok|Pelling|Darjeeling",
        Itinerary:
          "2N Gangtok . 2N Lachung . 1N Gangtok . 2N Pelling . 2N Darjeeling",
        "Places Covered": "Gangtok|Lachung|Gangtok|Pelling|Darjeeling",
        Travel_Date: "01-10-2021",
        Hotel_Details:
          "Lemon Tree Hotel  Gangtok:4.2|Jain Group Lachung Continental:3.3|Lemon Tree Hotel  Gangtok:4.2|The Aryan Regency:3.7|Ramada by Wyndham Darjeeling Gandhi Road:4.4",
        Start_City: "New Delhi",
        Airline: "Spicejet",
        "Flight Stops": "",
        "Onwards Return Flight Time": "05 : 30-10 : 10",
        Meals: "",
        Price_Per_Two_Persons: 71043,
        Per_Person_Price: 35521.5,
        "Sightseeing Places Covered":
          " Changu Lake - Excursion | Baba Mandir | Yumthang Valley ",
        "Initial Payment For Booking": "",
        "Cancellation Rules":
          "Cancellation any time after making the 1st payment instalment till the 2nd payment date:The entire amount paid as 1st payment instalment (deposit) would be non-refundable.Cancellation after 2nd payment instalment and before 3rd or final payment date:The total amount that was due at the 2nd payment instalment as per your payment schedule would be non-refundable; anything that you have paid over and above this amount would be refundable.Cancellation after 3rd or final payment date:The full amount paid by you would be non-refundable.",
        "Date Change Rules": "",
        FIELD23: "",
        FIELD24: "",
        FIELD25: "",
      },
    ],
  },
  {
    id: 2,
    title: "Mumbai",
    routeName: "mumbai",
    items: [
      {
        ID: 13,
        "Crawl Timestamp": "2021-09-25 16:15:44 +0000",
        "Package Name": "A Relaxing holiday to Kerala - Free Speed Boat Ride",
        Image_Url:
          "https://images.unsplash.com/photo-1638793770847-54861ae7cdf5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDI0fEZ6bzN6dU9ITjZ3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
        Package_Type: "Standard",
        Company: "Tralive",
        Destination: "Cochin|Munnar|Thekkady|Allepey|Kovalam and Poovar",
        Itinerary:
          "1N Cochin . 2N Munnar . 1N Thekkady . 1N Allepey . 2N Kovalam and Poovar",
        "Places Covered": "Cochin|Munnar|Thekkady|Allepey|Kovalam and Poovar",
        Travel_Date: "02-10-2021",
        Hotel_Details:
          "Quality Airport Hotel:4.1|Hotel Hillview, Munnar - MMT Special:4.1|Elephant Route Resort:3.8|Camelot Hotel, Alleppey- MMT Holidays Special:|Sagara Beach Resort:",
        Start_City: "Mumbai",
        Airline: "Spicejet|IndiGo",
        "Flight Stops": "",
        "Onwards Return Flight Time": "15 : 45-17 : 45|10 : 50-13 : 00",
        Meals: "",
        Price_Per_Two_Persons: 32864,
        Per_Person_Price: 16432,
        "Sightseeing Places Covered":
          " Dutch Palace | Jewish Synagogue | St. Francis Church | Chinese Fishing Nets | Fort Cochin | Mattupetty Dam | Tata Tea Museum | Pothamedu View Point | Eravikulam national park | Echo Point | Lakkam Waterfalls | Speed Boat Ride at Mattupetty Dam and Drive to Top Station in Munnar | Kalari Show | Periyar wildlife Sanctuary ",
        "Initial Payment For Booking": "",
        "Cancellation Rules":
          "Cancellation any time after making the 1st payment instalment till the 2nd payment date:The entire amount paid as 1st payment instalment (deposit) would be non-refundable.Cancellation after 2nd payment instalment and before 3rd or final payment date:The total amount that was due at the 2nd payment instalment as per your payment schedule would be non-refundable; anything that you have paid over and above this amount would be refundable.Cancellation after 3rd or final payment date:The full amount paid by you would be non-refundable.",
        "Date Change Rules": "",
        FIELD23: "",
        FIELD24: "",
        FIELD25: "",
      },
      {
        ID: 14,
        "Crawl Timestamp": "2021-09-26 04:18:42 +0000",
        "Package Name":
          "Experiential Manali from Chandigarh (Candid Photography)",
        Image_Url:
          "https://images.unsplash.com/photo-1641487941615-8161a491f67a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDI3fEZ6bzN6dU9ITjZ3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
        Package_Type: "Deluxe",
        Company: "Tralive",
        Destination: "Manali",
        Itinerary: "3N Manali",
        "Places Covered": "Manali",
        Travel_Date: "24-10-2021",
        Hotel_Details: "",
        Start_City: "Mumbai",
        Airline: "",
        "Flight Stops": "",
        "Onwards Return Flight Time": "",
        Meals: "",
        Price_Per_Two_Persons: 12045,
        Per_Person_Price: 6022.5,
        "Sightseeing Places Covered":
          " Vashishth Kund | Hadimba Temple | Tibetan Monastery | Personal Photoshoot in Manali | Solang Valley ",
        "Initial Payment For Booking": "",
        "Cancellation Rules":
          "This cancellation policy is applicable for bookings made for Weekend Getaways through the MakeMyTrip platform If the booking is made 15 days prior to the travel date (i.e. the date on which the customer is travelling):  When the customer has booked a weekend getaway 15 days (inclusive of the travel date) prior to the travel date, the customer is eligible to avail the benefit of this offer.At the time of making the payment while booking the package, the customer shall have the option of either paying in total or in instalments. If the customer chooses to make the payment in total and cancels the booking within 24 hours of making the payment, the customer shall be entitled to get the full refund under this offer. In case of any flight bookings, MakeMyTrip shall, in its sole discretion, refund partial booking amount to the customer. Full refund under the offer is not applicable on Air Asia, Scoot Airlines, Nok-Scoot and Tiger Australia.  If a customer chooses to make the payment in instalments and cancels the booking thereafter, MakeMyTrip shall provide the refund in the following manner:When the customer has made 1st instalment of the booking amount and the booking is cancelled within 24 hours of making the booking, MakeMyTrip shall refund the full amount paid in the 1st instalment. However, In case of any flight bookings, MakeMyTrip shall, in its sole discretion, refund partial booking amount to the customer. Full refund under the offer is not applicable on Air Asia, Scoot Airlines, Nok-Scoot & Tiger Australia.  When the customer has made 1st instalment of the booking amount and the booking is cancelled after 24 hours of making the booking but before making the 2nd instalment, the entire 1st instalment shall be non-refundable.  When the customer cancels the booking upon paying the 2nd instalment but before paying the 3rd instalment, the amount of 1st and 2nd instalment as paid by the customer shall be non-refundable. However, if the customer has paid an amount over and above the amount to be paid for the 1st and 2nd instalment, MakeMyTrip shall refund the said amount.  When the customer cancels the booking upon paying the 3rd instalment, the entire booking amount paid shall be non-refundable.  If the booking is made within 15 days from the travel date:   When the customer has made 1st instalment of the booking amount and the booking is cancelled before making the 2nd instalment, the entire 1st instalment shall be non-refundable.  When the customer cancels the booking upon paying the 2nd instalment but before paying the 3rd instalment, the amount of 1st and 2nd instalment as paid by the customer shall be non-refundable. However, if the customer has paid an amount over and above the amount to be paid for the 1st and 2nd instalment, MakeMyTrip shall refund the said amount.When the customer cancels the booking upon paying the 3rd instalment, the entire booking amount paid shall be non-refundable.",
        "Date Change Rules": "",
        FIELD23: "",
        FIELD24: "",
        FIELD25: "",
      },
      {
        ID: 15,
        "Crawl Timestamp": "2021-09-25 12:45:50 +0000",
        "Package Name": "Best of Holiday in Himachal from Chandigarh",
        Image_Url:
          "https://images.unsplash.com/photo-1605649487212-47bdab064df7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8aGltYWNoYWx8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
        Package_Type: "Standard",
        Company: "Tralive",
        Destination: "Shimla|Manali|Dharamshala|Dalhousie|Chandigarh",
        Itinerary:
          "2N Shimla . 3N Manali . 2N Dharamshala . 2N Dalhousie . 1N Chandigarh",
        "Places Covered": "Shimla|Manali|Dharamshala|Dalhousie|Chandigarh",
        Travel_Date: "13-10-2021",
        Hotel_Details: "",
        Start_City: "Mumbai",
        Airline: "",
        "Flight Stops": "",
        "Onwards Return Flight Time": "",
        Meals: "",
        Price_Per_Two_Persons: 35725,
        Per_Person_Price: 17862.5,
        "Sightseeing Places Covered":
          " Pinjore Gardens | Mall road | Kufri | Indira Bunglow | Himalayan Zoo | Mall road | Shimla Church | Scandal point | Gaeity Theatre | Townhall | Mall road | Vashishth Kund | Hadimba Temple | Jakhoo Temple ",
        "Initial Payment For Booking": "",
        "Cancellation Rules":
          "Cancellation any time after making the 1st payment instalment till the 2nd payment date:The entire amount paid as 1st payment instalment (deposit) would be non-refundable.Cancellation after 2nd payment instalment and before 3rd or final payment date:The total amount that was due at the 2nd payment instalment as per your payment schedule would be non-refundable; anything that you have paid over and above this amount would be refundable.Cancellation after 3rd or final payment date:The full amount paid by you would be non-refundable.",
        "Date Change Rules": "",
        FIELD23: "",
        FIELD24: "",
        FIELD25: "",
      },
      {
        ID: 16,
        "Crawl Timestamp": "2021-09-25 01:12:03 +0000",
        "Package Name": "A Journey to Cochin, Thekkady and Allepey",

        Image_Url:
          "https://images.unsplash.com/photo-1585637850919-66f56fe273c9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8Y29jaGlufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
        Package_Type: "Standard",
        Company: "Tralive",
        Destination: "Cochin|Thekkady|Allepey",
        Itinerary: "1N Cochin . 2N Thekkady . 1N Allepey",
        "Places Covered": "Cochin|Thekkady|Allepey",
        Travel_Date: "30-09-2021",
        Hotel_Details:
          "Holidays Special Offer",
        Start_City: "Mumbai",
        Airline: "Spicejet",
        "Flight Stops": "",
        "Onwards Return Flight Time": "09 : 20-11 : 25",
        Meals: "",
        Price_Per_Two_Persons: 18222,
        Per_Person_Price: 9111,
        "Sightseeing Places Covered":
          " Fort Cochin | Dutch Palace | Jewish Synagogue | St. Francis Church | Chinese Fishing Nets ",
        "Initial Payment For Booking": "",
        "Cancellation Rules":
          "Cancellation any time after making the 1st payment instalment till the 2nd payment date:The entire amount paid as 1st payment instalment (deposit) would be non-refundable.Cancellation after 2nd payment instalment and before 3rd or final payment date:The total amount that was due at the 2nd payment instalment as per your payment schedule would be non-refundable; anything that you have paid over and above this amount would be refundable.Cancellation after 3rd or final payment date:The full amount paid by you would be non-refundable.",
        "Date Change Rules": "",
        FIELD23: "",
        FIELD24: "",
        FIELD25: "",
      },
      {
        ID: 17,
        "Crawl Timestamp": "2021-09-26 09:01:08 +0000",
        "Package Name": "Kodaikanal and Madurai Holiday",
        Image_Url:
          "https://images.unsplash.com/photo-1629064511726-841ce84f39df?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8Y29jaGlufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
        Package_Type: "Premium",
        Company: "Tralive",
        Destination: "Kodaikanal|Madurai",
        Itinerary: "2N Kodaikanal . 1N Madurai",
        "Places Covered": "Kodaikanal|Madurai",
        Travel_Date: "04-10-2021",
        Hotel_Details:
          "The Tamara Kodai:4.6|The Gateway Hotel Pasumalai Madurai:4.5",
        Start_City: "Mumbai",
        Airline: "IndiGo|IndiGo",
        "Flight Stops": "",
        "Onwards Return Flight Time": "00 : 45-02 : 40|05 : 35-07 : 15",
        Meals: "",
        Price_Per_Two_Persons: 44047,
        Per_Person_Price: 22023.5,
        "Sightseeing Places Covered":
          " Silver Cascade Falls | Kodaikanal Lake | Coakers Walk | Dolphins Nose | Pillar Rock | Meenakshi Temple ",
        "Initial Payment For Booking": "",
        "Cancellation Rules":
          "Cancellation any time after making the 1st payment instalment till the 2nd payment date:The entire amount paid as 1st payment instalment (deposit) would be non-refundable.Cancellation after 2nd payment instalment and before 3rd or final payment date:The total amount that was due at the 2nd payment instalment as per your payment schedule would be non-refundable; anything that you have paid over and above this amount would be refundable.Cancellation after 3rd or final payment date:The full amount paid by you would be non-refundable.",
        "Date Change Rules": "",
        FIELD23: "",
        FIELD24: "",
        FIELD25: "",
      },
      {
        ID: 18,
        "Crawl Timestamp": "2021-09-27 15:02:15 +0000",
        "Package Name": "A Grand Week in Sri Lanka - Bentota & Kandy Special",
        "Information":"The Surf Bentota-MMT HOLIDAYS SPECIAL:4.0|Tree Of Life Nature-MMT HOLIDAYS SPECIAL:|Ozo Colombo  (MMT HOLIDAYS SPECIAL):",
        Image_Url:
        "https://images.unsplash.com/photo-1623595289196-007a22dd8560?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8c3JpbGFua2F8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
          
        Package_Type:
        "Luxury",
        Company: "Tralive",
        Destination: "Colombo",
        Itinerary: "Bentota|Kandy|Colombo",
        "Places Covered": "3N Bentota . 3N Kandy . 1N Colombo",
        Travel_Date: "Bentota|Kandy|Colombo",
        Hotel_Details: "27-10-2021",
        Start_City: "Mumbai",
        Airline: "IndiGo|IndiGo|IndiGo|IndiGo",
        "Flight Stops": "",
        "Onwards Return Flight Time":
          "06 : 10-08 : 10|12 : 00-13 : 25|09 : 30-11 : 05|17 : 15-19 : 15",
        Meals: "",
        Price_Per_Two_Persons: 72015,
        Per_Person_Price: 35007.5,
        "Sightseeing Places Covered": "",
        "Initial Payment For Booking": "",
        "Cancellation Rules":
          "Cancellation any time after making the 1st payment installment till the 2nd payment date:The entire amount paid as 1st payment instalment (deposit) would be non-refundable.Cancellation after 2nd payment instalment and before 3rd or final payment date:The total amount that was due at the 2nd payment instalment as per your payment schedule would be non-refundable; anything that you have paid over and above this amount would be refundable.Cancellation after 3rd or final payment date:The full amount paid by you would be non-refundable.",
        "Date Change Rules": "",
        FIELD23: "",
        FIELD24: "",
        FIELD25: "",
      },
      {
        ID: 19,
        "Crawl Timestamp": "2021-09-27 15:38:13 +0000",
        "Package Name":
          "North East with Shillong and Kaziranga - Wildlife (Online)",
          "Information":"HOTEL GATEWAY SHILLONG:3.4|IORA Retreat Kaziranga:4.4",
        Image_Url: 
        "https://images.unsplash.com/photo-1629631800396-48e28b337673?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fGNvY2hpbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
        
        Package_Type:"Luxury",
        
        Company: "Tralive",
        Destination: "Kaziranga",
        Itinerary: "Shillong|Kaziranga",
        "Places Covered": "2N Shillong . 2N Kaziranga",
        Travel_Date: "Shillong|Kaziranga",
        Hotel_Details: "15-10-2021",
        Start_City: "Mumbai",
        Airline: "Spicejet",
        "Flight Stops": "",
        "Onwards Return Flight Time": "11 : 15-14 : 25",
        Meals: "",
        Price_Per_Two_Persons: 38611,
        Per_Person_Price: 19305.5,
        "Sightseeing Places Covered":
          " Umiam Lake | Elephant Falls | Shillong Peak | Seven Sister Falls | Nohkalikai Waterfalls, Cherrapunji | Mawsmai Cave, Cherrapunji | Thankarang Park | Duwan Sing Syiem view point | Kaziranga national park | Kaziranga National Park Visit with Elephant and Jeep Safari (With Transfers) ",
        "Initial Payment For Booking": "",
        "Cancellation Rules":
          "Cancellation any time after making the 1st payment instalment till the 2nd payment date:The entire amount paid as 1st payment instalment (deposit) would be non-refundable.Cancellation after 2nd payment instalment and before 3rd or final payment date:The total amount that was due at the 2nd payment instalment as per your payment schedule would be non-refundable; anything that you have paid over and above this amount would be refundable.Cancellation after 3rd or final payment date:The full amount paid by you would be non-refundable.",
        "Date Change Rules": "",
        FIELD23: "",
        FIELD24: "",
        FIELD25: "",
      },
    ],
  },
];

export default TRAVEL_DATA;
